### ISSUE TITLE
PURGE function causes exception

### ISSUE THREAD

**Issue by brownounces** [izzyreal/vmpc-juce#71] opened 2023-04-10 22:37 UTC
There appears to be an issue with the PURGE function in the PROGRAM feature (and possibly deleting samples from the TRIM feature) which causes a crash. It seems to exist on both W10 and W11, on the latest public and dev builds.

Steps to replicate:
1. Sample or import a sound into VMPC and do not assign it to any program.
1. Under PROGRAM, PURGE exists to remove samples not currently used by any program.
2. Select this function and delete the unneeded samples.
3. Depart from the PROGRAM feature back to the sequencer.
4. In a few seconds (or with some cursor/data wheel activity), VMPC should crash.

This also happens frequently if I delete a sample from the TRIM feature, but not all of the time.

My guess (which is as valuable as nothing more than an armchair developer's theory) is that, for some reason, the internal sample array is not updated to reflect the deleted samples, causing an exception when VMPC attempts to read or check a sample which no longer exists.

**Comment by izzyreal** [comment] 2023-04-11 11:27
Starting with a clean slate (no sounds, no sequences, only the default Program) I can't reproduce it using the steps you provided. Using latest dev build on Windows 10 and macOS 13. I discovered [this bug](https://github.com/izzyreal/mpc/issues/168) though.

Are the reproduction steps reliable for you?

**Comment by brownounces** [comment] 2023-04-11 17:58
Actually, you are correct -- it appears to be working fine on the latest dev build after I've deleted old VMPC settings and files which possibly contained some corrupt data. I think the fix you employed to change how VMPC handles filenames also fixed this problem.

It does still crash for me on older builds though; try replicating my steps on the latest public build and see if it crashes for you. It could possibly be something on my end that isn't jiving with the older builds though if it is still working for you.

**Comment by izzyreal** [comment] 2023-04-11 19:06
I'm only testing on the latest build. If it works there (indeed possibly
after cleaning settings etc like you did), things are fine.

**Comment by izzyreal** [comment] 2023-04-11 20:28
_Internal note:_ Refer to `BEAT1.7z` as sent via email to reproduce this issue.

**Comment by izzyreal** [comment] 2023-04-12 23:17
I was doing very silly stuff in `Sampler::purge()`. I think all should be resolved in 0b649c7efb2a3434ba4c106ffac0c0e4aa8c47e6. Will hit you up with a dev build soon.

**Comment by brownounces** [comment] 2023-04-12 23:47
Esplendido. Don't be a silly goose Izzy!

**Comment by izzyreal** [comment] 2023-04-12 23:55
Please confirm it's working for you: https://drive.google.com/file/d/1DWYQHtHMskR4QgBCeyd1j9GAUHPOVCx8/view?usp=sharing

**Comment by brownounces** [comment] 2023-04-13 01:51
That new build fixed it! I experienced a crash after PURGE and switching to the SAVE screen one time, but I haven't actually been able to reproduce it. It seems to have been an isolated crash, but I'll report anything else that happens.

**Comment by izzyreal** [comment] 2023-04-13 02:20
The crash sounds nasty. It's a shame crash reports with stacktraces on Windows are [far from trivial to accomplish](https://stackoverflow.com/questions/24208767/get-stack-trace-of-a-crash-on-windows-without-installing-visual-studio-c). On macOS you get 'm for free. Would be great if we find out what that crash was about.

Glad the purge works 👌 Will close this issue.

**Closed by izzyreal** 2023-04-13 02:20 UTC
