### ISSUE TITLE
Settings wheel doesn't display settings (distro specific?)

### ISSUE THREAD

**Issue by brownounces** [izzyreal/vmpc-juce#91] opened 2023-05-27 01:44 UTC
On the Linux build, it seems that the settings wheel on VMPC does not work on some distributions or configurations. Most of the time when clicked, it will spawn a blank dialog box for a moment before closing. When the settings button is spammed, it will sometimes display properly.

Some notes on this: 

1. The settings wheel seems to _almost never_ open on Wayland, but occasionally opens when spammed on Xorg. 
2. It seems to be distro, configuration, or package specific -- @izzyreal notes that it does work on his Arch and Ubuntu installations. I have this problem on Gentoo, and it has persisted across fresh system installs of the distro.
3. No error or exception is reported when VMPC is run from a terminal. It simply aborts this one function quietly.

**Comment by brownounces** [comment] 2023-06-10 04:16
After properly setting up Jack and switching to it via Xorg, this bug seems to resolved itself. My only insight is that the settings wheel may only have issues when the ALSA device is the currently selected.

**Comment by izzyreal** [comment] 2023-10-07 10:12
@brownounces Do you still experience this issue? I'm inclined to close the issue since I have not been able to reproduce it (including on Wayland + ALSA).

**Comment by izzyreal** [comment] 2023-10-22 06:59
Closing this due to inactivity. Feel free to reopen it if it's still relevant.

**Closed by izzyreal** 2023-10-22 06:59 UTC
Labels: can't reproduce
