### ISSUE TITLE
Import 24bit wav audio causing crash

### ISSUE THREAD

**Issue by michaelmon1203** [izzyreal/vmpc-juce#42] opened 2022-05-09 03:45 UTC
Hi, really love your work, just want to report an issue, VMPC crashes every time I import 24bit wav audio file like this. I import file through drag and drop from my Finder, Mac Big Sur.

[Snares565.WAV.zip](https://github.com/izzyreal/vmpc-juce/files/8648619/Snares565.WAV.zip)

**Comment by michaelmon1203** [comment] 2022-05-09 05:47
I just found the solution, need to set convert WAV on, otherwise it will crash. I think this option should be on by default, people might think it is buggy and quit using vmpc.

**Comment by izzyreal** [comment] 2022-05-09 06:21
Thanks for reporting this @michaelmon1203. I am able to reproduce the issue. The intended behaviour when "Auto-convert WAVs" is disabled here https://vmpcdocs.izmar.nl/vmpc_specific_settings.html#auto-convert-wavs, is that a prompt will ask what you want to do.

I'll take a look at this bug soon and report back here.

**Comment by izzyreal** [comment] 2022-05-14 12:26
@michaelmon1203 I've published v0.4.4 which includes a fix for this issue. See https://izmar.nl/downloads

**Comment by izzyreal** [comment] 2022-05-14 16:14
@michaelmon1203 Apologies, I had to roll back 0.4.4... I introduced a bug in the audio engine. I hope to fix it within a week.

**Comment by izzyreal** [comment] 2022-05-14 17:29
@michaelmon1203 Ok it's fixed. 0.4.4 is published and it should fix this issue.

**Comment by izzyreal** [comment] 2022-05-15 12:08
Resolved in https://github.com/izzyreal/mpc/commit/844ef07f9cd39cadc5308b9de8517db76505ecc9

**Closed by izzyreal** 2022-05-15 12:08 UTC
Labels: bug, crash
