### ISSUE TITLE
16 levels fails to record properly

### ISSUE THREAD

**Issue by brownounces** [izzyreal/vmpc-juce#77] opened 2023-04-19 14:35 UTC
On the latest CMake build, it appears that the 16 LEVELS function has broken during record. Rather than record the pad being played in a different pitch, it records the original sample (if any is assigned) that the pad holds.

Steps to reproduce:
1. Drop a sample (normally a one-shot bass) onto a pad. I normally use BANK B for drum sounds.
2. Press 16 levels, select the pad that contains the sample and scroll to TUNING
3. Go back to BANK A (if you assigned the sound to BANK B like I did)
4. Record the different pitches being played of the sound
5. When the recording is complete, press PLAY
6. No sound (or the sound originally on the bank, if one is loaded) will play rather than the sample selected for 16 LEVELS, and the STEP function demonstrates that it is not tuning the sample either

Should be easy to revert the offending change, if one was made, because this function worked perfectly before.

**Comment by izzyreal** [comment] 2023-04-19 19:45
Duplicate of https://github.com/izzyreal/mpc/issues/181

**Closed by izzyreal** 2023-04-19 19:45 UTC
